/* Bharat: 10,000 Years — Historical Figures (42) with Who Am I? clues */
window.BHARAT_FIGURES = [
  { id:"chanakya", name:"Chanakya (Kautilya)", era:"maurya", years:"-375 to -283 BCE", region:"north",
    themes:["science","trade"], summary:"Strategist, economist, and kingmaker who authored the Arthashastra and engineered the rise of the Maurya Empire.",
    clues:["I wrote the most ruthless political treatise of the ancient world.","I studied at Takshashila and swore revenge after a king's insult.","I made a nobody into an emperor and ran his empire from behind the throne.","My student overthrew the Nanda dynasty."] },
  { id:"chandragupta-maurya", name:"Chandragupta Maurya", era:"maurya", years:"-340 to -298 BCE", region:"north",
    themes:["trade"], summary:"Founder of the Maurya Empire, who defeated Alexander's successors and built India's first subcontinental state.",
    clues:["I founded India's largest ancient empire.","I defeated Seleucus Nicator and received his daughter in marriage.","My teacher was the author of the Arthashastra.","I renounced my throne to become a Jain ascetic at Shravanabelagola."] },
  { id:"ashoka", name:"Ashoka", era:"maurya", years:"-304 to -232 BCE", region:"north",
    themes:["spiritual","trade"], summary:"The Maurya emperor who, shattered by the carnage of Kalinga, transformed from conqueror to evangelist of non-violence and dharma.",
    clues:["A single battle changed me from warrior to peacemaker.","My edicts are carved on rocks and pillars across the subcontinent.","I sent my children to carry the dharma to Sri Lanka.","My lion capital became my country's national emblem two millennia later."] },
  { id:"samudragupta", name:"Samudragupta", era:"gupta", years:"335–375 CE", region:"north",
    themes:["trade","art"], summary:"The 'Napoleon of India' who expanded the Gupta Empire through sweeping military campaigns recorded in the Allahabad Pillar inscription.",
    clues:["Historians called me the Napoleon of India.","My military exploits are inscribed on an Ashokan pillar at Allahabad.","I played the veena and was a poet as well as a conqueror.","I was the second emperor of India's golden-age dynasty."] },
  { id:"chandragupta-ii", name:"Chandragupta II Vikramaditya", era:"gupta", years:"375–415 CE", region:"north",
    themes:["art","science","trade"], summary:"The Gupta emperor under whose reign India's classical golden age reached its peak — patron of Kalidasa, Aryabhata, and Nalanda.",
    clues:["My court was home to the 'Nine Gems' of learning.","A Chinese pilgrim visited my kingdom and called it the happiest on Earth.","I share a title with a legendary king whose era begins the Vikram calendar.","An iron pillar that still refuses to rust was raised in my honor."] },
  { id:"aryabhata", name:"Aryabhata", era:"gupta", years:"476–550 CE", region:"east",
    themes:["science"], summary:"Mathematician and astronomer who proposed a place-value system, approximated pi, and argued that the Earth rotates on its axis.",
    clues:["India's first satellite was named after me.","I wrote that the Earth turns on its axis, not the sky.","I approximated pi to four decimal places at age 23.","My treatise, written in 499 CE, transformed mathematics."] },
  { id:"kalidasa", name:"Kalidasa", era:"gupta", years:"~4th–5th century CE", region:"north",
    themes:["language","art"], summary:"India's greatest classical Sanskrit poet and playwright, author of Shakuntala, Meghaduta, and Raghuvamsha.",
    clues:["Goethe praised my most famous play as containing 'heaven and earth.'","I wrote about a cloud carrying a love message across the monsoon sky.","My plays are considered the peak of classical Sanskrit literature.","I am often called the Shakespeare of India, though I came a thousand years earlier."] },
  { id:"adi-shankaracharya", name:"Adi Shankaracharya", era:"regional-empires", years:"788–820 CE", region:"south",
    themes:["spiritual"], summary:"The philosopher-monk who unified Hindu philosophy under Advaita Vedanta and established four monastic centres at the compass points of India.",
    clues:["I walked the length and breadth of India — twice — before I turned thirty.","I established four monasteries at the four corners of the subcontinent.","I was born in Kerala and debated scholars from Kashmir to Kashi.","My philosophy says the individual self and the universal reality are one."] },
  { id:"rajaraja-chola", name:"Rajaraja Chola I", era:"regional-empires", years:"947–1014 CE", region:"south",
    themes:["trade","art"], summary:"The Chola emperor who built the Brihadeeswara Temple and launched the imperial expansion that made the Cholas the dominant power of the Indian Ocean.",
    clues:["I built a temple with an 80-tonne capstone and no crane.","My navy controlled the sea routes from India to Southeast Asia.","My son extended my empire even further, across the Bay of Bengal.","I ruled from Thanjavur and commissioned the tallest temple of its age."] },
  { id:"rajendra-chola", name:"Rajendra Chola I", era:"regional-empires", years:"971–1044 CE", region:"south",
    themes:["trade"], summary:"Son of Rajaraja I, Rajendra sent naval expeditions to Southeast Asia and marched north to the Ganges, earning the title Gangaikonda.",
    clues:["I defeated the Srivijaya maritime empire across the Bay of Bengal.","I took the title 'He who conquered the Ganges.'","I built a new capital to celebrate my northern campaign.","My father built the Brihadeeswara; I built its rival at my new capital."] },
  { id:"gargi", name:"Gargi Vachaknavi", era:"vedic", years:"~800 BCE", region:"north",
    themes:["spiritual","women","science"], summary:"One of history's earliest recorded women philosophers, who publicly debated the sage Yajnavalkya in the court of King Janaka.",
    clues:["I debated the greatest sage of my age — in public, before a king.","My questions about the nature of reality are preserved in the Upanishads.","I am one of the earliest women philosophers in recorded history.","The sage I challenged warned me my head would shatter if I asked one more question."] },
  { id:"panini", name:"Panini", era:"mahajanapadas", years:"~500 BCE", region:"north",
    themes:["language","science"], summary:"The grammarian who distilled Sanskrit into ~4,000 algebraic rules, anticipating modern computer science by 2,500 years.",
    clues:["I wrote fewer than 4,000 rules and captured an entire language.","Computer scientists say my work anticipates programming language design.","I studied at Takshashila, in the far northwest.","My grammar of Sanskrit has been called the most complete grammar of any language ever written."] },
  { id:"buddha", name:"Siddhartha Gautama (The Buddha)", era:"mahajanapadas", years:"~563–483 BCE", region:"north",
    themes:["spiritual"], summary:"The prince who renounced his kingdom, attained enlightenment at Bodh Gaya, and founded a spiritual tradition that spread across all of Asia.",
    clues:["I left a palace to sit under a tree, and what I found there changed the world.","My first sermon turned the wheel of dharma at a deer park.","I was born a prince of the Shakya clan at the foot of the Himalayas.","My final words urged my followers to 'strive on with diligence.'"] },
  { id:"mahavira", name:"Mahavira", era:"mahajanapadas", years:"~599–527 BCE", region:"east",
    themes:["spiritual"], summary:"The 24th Tirthankara of Jainism, who taught radical non-violence toward all living beings.",
    clues:["I am the last of twenty-four teachers in my tradition.","I taught that even the smallest insect deserves non-violence.","I was born a prince in Bihar, like my contemporary across the Gangetic plain.","My followers sweep the ground before them to avoid harming any creature."] },
  { id:"guru-nanak", name:"Guru Nanak", era:"sultanate", years:"1469–1539 CE", region:"north",
    themes:["spiritual"], summary:"Founder of Sikhism, who traversed the known world to preach one God, equality, and service to all.",
    clues:["I traveled to Mecca, Baghdad, and Tibet on four great journeys.","I declared there is no Hindu, there is no Muslim — only seekers.","I was born in Punjab and founded a tradition followed by 30 million today.","My first companion was a Muslim musician named Mardana."] },
  { id:"kabir", name:"Kabir", era:"sultanate", years:"~1398–1518 CE", region:"north",
    themes:["spiritual","language"], summary:"Weaver-poet of Varanasi who challenged caste and religious hypocrisy with fierce, luminous couplets in vernacular Hindi.",
    clues:["I wove cloth and wove words, both with equal skill.","Both Hindus and Muslims claim me — I claimed neither label.","My two-line couplets are still sung by people who don't know my name.","I lived in Varanasi and challenged every priest and mullah I met."] },
  { id:"rana-kumbha", name:"Rana Kumbha", era:"sultanate", years:"1433–1468 CE", region:"north",
    themes:["art","trade"], summary:"The warrior-scholar king of Mewar who built 32 forts, composed music treatises, and raised the Vijay Stambha at Chittorgarh.",
    clues:["I built 32 of Mewar's 84 forts.","I raised a victory tower nine stories tall, carved with Hindu deities.","I was a musician who composed scholarly treatises on ragas.","I ruled from Chittorgarh, the most celebrated fortress in Rajput lore."] },
  { id:"rudrama-devi", name:"Rudrama Devi", era:"sultanate", years:"1245–1289 CE", region:"center",
    themes:["women","trade"], summary:"The warrior-queen of the Kakatiya dynasty who ruled Warangal for over two decades, commanding armies and repelling invasions.",
    clues:["Marco Polo wrote about my well-governed kingdom.","I ruled a Telugu kingdom for over two decades.","My father appointed me his successor over male heirs.","I led my armies in person from the fortress of Warangal."] },
  { id:"krishnadevaraya", name:"Krishnadevaraya", era:"sultanate", years:"1471–1529 CE", region:"south",
    themes:["trade","language","art"], summary:"The greatest Vijayanagara emperor, warrior-king and Telugu poet, whose reign marked the empire's golden age.",
    clues:["Foreign travelers said my capital rivaled Rome in grandeur.","I wrote a masterwork of Telugu literature, Amuktamalyada.","My court hosted poets in four languages simultaneously.","I ruled the empire whose capital was called the City of Victory."] },
  { id:"maharana-pratap", name:"Maharana Pratap", era:"mughal", years:"1540–1597 CE", region:"north",
    themes:["trade"], summary:"The Rajput king of Mewar who never submitted to Mughal authority, fighting from exile with guerrilla resistance until he recovered most of his kingdom.",
    clues:["I fought the Mughals at Haldighati and never surrendered.","My horse Chetak is honored with his own memorial.","I ate bread made from wild grass seeds during my years of exile.","I was the Rana of Mewar who chose freedom in the forest over a comfortable submission."] },
  { id:"shivaji", name:"Chhatrapati Shivaji Maharaj", era:"mughal", years:"1630–1680 CE", region:"west",
    themes:["trade"], summary:"Founder of the Maratha swarajya, who built an independent kingdom through guerrilla warfare, naval power, and enlightened administration.",
    clues:["I built my first fort capture at the age of seventeen.","I established swarajya — self-rule — against the Mughal Empire.","I was crowned Chhatrapati in a Vedic ceremony at Raigad.","I built one of the first indigenous Indian navies in centuries."] },
  { id:"lachit-borphukan", name:"Lachit Borphukan", era:"mughal", years:"1622–1672 CE", region:"northeast",
    themes:["trade"], summary:"The Ahom general who defeated the Mughal navy at the Battle of Saraighat on the Brahmaputra, preserving northeastern India's independence.",
    clues:["I defeated the Mughal navy on the Brahmaputra.","I beheaded my own uncle for collaborating with the enemy.","My battle saved the northeast from Mughal conquest.","The Indian National Defence Academy gives a gold medal in my name."] },
  { id:"guru-gobind-singh", name:"Guru Gobind Singh", era:"mughal", years:"1666–1708 CE", region:"north",
    themes:["spiritual"], summary:"The tenth and last human Sikh Guru, who founded the Khalsa, declared the Guru Granth Sahib as the eternal Guru, and sacrificed his family for his faith.",
    clues:["I founded a brotherhood defined by five articles of faith.","I declared a holy book to be my eternal successor.","All four of my sons died fighting or were executed.","I asked for five heads — and received five volunteers."] },
  { id:"rani-abbakka", name:"Rani Abbakka Chowta", era:"mughal", years:"~1525–1570 CE", region:"south",
    themes:["women","trade"], summary:"The fearless queen of Ullal who repelled Portuguese invasions of the Karnataka coast for four decades.",
    clues:["I fought the Portuguese for forty years along the Malabar coast.","I was the queen of a small kingdom in Karnataka, but no European could conquer it.","I used guerrilla tactics and night raids against colonial invaders centuries before others.","The Portuguese called me 'the undaunted one.'"] },
  { id:"ahilyabai-holkar", name:"Ahilyabai Holkar", era:"mughal", years:"1725–1795 CE", region:"center",
    themes:["women","trade","spiritual"], summary:"The philosopher-queen of Indore who rebuilt temples across India, reformed administration, and gave her people three decades of justice and prosperity.",
    clues:["I ruled Indore for 30 years and rebuilt temples from Varanasi to Dwarka.","I was a widowed queen who governed so wisely that my subjects called me a saint.","I personally heard public petitions and administered justice every day.","My kingdom was so well-run that John Malcolm called it the finest he had ever seen in India."] },
  { id:"sushruta", name:"Sushruta", era:"vedic", years:"~600 BCE", region:"north",
    themes:["science"], summary:"The ancient surgeon of Varanasi, author of the Sushruta Samhita, who described over 300 surgical procedures including rhinoplasty — the world's first recorded plastic surgery.",
    clues:["I described how to reconstruct a nose using a flap from the forehead.","My surgical textbook lists over 120 surgical instruments.","I practised at Varanasi and is considered the father of surgery.","My technique for rhinoplasty was re-discovered by European surgeons in the 18th century."] },
  { id:"brahmagupta", name:"Brahmagupta", era:"regional-empires", years:"598–668 CE", region:"north",
    themes:["science"], summary:"The mathematician who formalized the rules for zero and negative numbers, making the modern number system possible.",
    clues:["I wrote the rules for adding, subtracting, and multiplying with zero.","Without my work, modern mathematics and computing would not exist.","I worked at the astronomical center at Ujjain.","I was the first to treat zero as a number, not just a placeholder."] },
  { id:"gandhi", name:"Mahatma Gandhi", era:"colonial", years:"1869–1948 CE", region:"west",
    themes:["spiritual","trade"], summary:"The lawyer-turned-ascetic who led India's freedom struggle through satyagraha — truth-force — inspiring non-violent resistance movements worldwide.",
    clues:["I walked 390 kilometres to pick up salt and break an empire's law.","My weapon was truth and non-violence, and I fought a world power with it.","I called myself a 'half-naked fakir' and made the charkha a symbol of self-reliance.","I was shot in a garden in Delhi, six months after the freedom I had spent my life seeking."] },
  { id:"tilak", name:"Bal Gangadhar Tilak", era:"colonial", years:"1856–1920 CE", region:"west",
    themes:["trade","language"], summary:"The 'Father of Indian Unrest' who declared 'Swaraj is my birthright' and transformed the independence movement from polite petitioning to mass mobilization.",
    clues:["I declared swaraj as my birthright, and I shall have it.","The British called me the father of Indian unrest — I took it as a compliment.","I started the Ganesh Chaturthi festival as a public, political gathering.","I was a mathematician, Sanskrit scholar, and editor who spent years in Mandalay prison."] },
  { id:"bose", name:"Subhas Chandra Bose (Netaji)", era:"colonial", years:"1897–1945 CE", region:"east",
    themes:["trade"], summary:"The revolutionary leader who formed the Indian National Army and the Azad Hind government-in-exile, pursuing armed liberation from colonial rule.",
    clues:["I formed a government-in-exile and an army to free India by force.","I escaped British house arrest in a dramatic disguise through Afghanistan.","My army included an all-women regiment named after a warrior queen.","I gave the call: 'Give me blood, and I shall give you freedom.'"] },
  { id:"bhagat-singh", name:"Bhagat Singh", era:"colonial", years:"1907–1931 CE", region:"north",
    themes:["trade"], summary:"The young revolutionary who threw smoke bombs in the Central Assembly, refused to appeal his death sentence, and walked smiling to the gallows at 23.",
    clues:["I was reading Lenin's biography when they came to take me to the gallows.","I threw a bomb in parliament — designed not to kill, but to make the deaf hear.","I was 23 when the British hanged me, along with my two comrades.","I wrote 'Why I Am an Atheist' in my death-row cell."] },
  { id:"patel", name:"Sardar Vallabhbhai Patel", era:"republic", years:"1875–1950 CE", region:"west",
    themes:["trade"], summary:"The Iron Man of India who unified 565 princely states into the Indian Union through a combination of negotiation, persuasion, and unflinching resolve.",
    clues:["I stitched 565 kingdoms into one nation in under two years.","They called me the Iron Man of India.","I was a farmer's son from Gujarat who became India's first Deputy Prime Minister.","The world's tallest statue — 182 metres — was built in my likeness."] },
  { id:"ambedkar", name:"Dr. B.R. Ambedkar", era:"republic", years:"1891–1956 CE", region:"center",
    themes:["trade","spiritual"], summary:"Dalit scholar, constitutional architect, and social revolutionary who overcame caste oppression to author the world's longest written constitution.",
    clues:["I studied 60 constitutions to write the world's longest one.","I overcame caste discrimination to earn doctorates from Columbia and London.","I burned the Manusmriti in public protest and later embraced Buddhism.","I is remembered as the architect of the Indian Constitution."] },
  { id:"nehru", name:"Jawaharlal Nehru", era:"republic", years:"1889–1964 CE", region:"north",
    themes:["trade","science"], summary:"India's first Prime Minister, who spoke of a 'tryst with destiny' at midnight and shaped the republic's democratic, secular, scientific vision.",
    clues:["My midnight speech on independence is among history's most famous.","I spoke of a tryst with destiny as the clock struck twelve.","I built dams and called them the temples of modern India.","Children across India call me Chacha."] },
  { id:"vikram-sarabhai", name:"Vikram Sarabhai", era:"republic", years:"1919–1971 CE", region:"west",
    themes:["science"], summary:"The father of the Indian space programme, who convinced a skeptical world that a developing nation needed rockets not for weapons, but for development.",
    clues:["I founded India's space programme from a fishing village in Kerala.","My first rockets were transported on bicycles and bullock carts.","I said India must be second to none in space technology.","The space centre at Thiruvananthapuram is named after me."] },
  { id:"kalam", name:"A.P.J. Abdul Kalam", era:"republic", years:"1931–2015 CE", region:"south",
    themes:["science"], summary:"The 'Missile Man' who led India's space and defence programmes, then became the People's President — a scientist who dreamed of an India in 2020.",
    clues:["I was a rocket scientist who became the President of India.","I dreamed of India as a developed nation by 2020.","I was born in Rameswaram and sold newspapers as a boy.","They called me the Missile Man, but I wanted to be remembered as a teacher."] },
  { id:"swaminathan", name:"M.S. Swaminathan", era:"republic", years:"1925–2023 CE", region:"south",
    themes:["science"], summary:"The father of India's Green Revolution, whose high-yield wheat varieties transformed a famine-prone nation into a food-surplus power.",
    clues:["I turned India from a country begging for food aid into a food exporter.","I introduced high-yield wheat varieties that tripled Punjab's harvest.","I am called the father of India's Green Revolution.","My work saved millions from the famines that had haunted India for centuries."] },
  { id:"kurien", name:"Verghese Kurien", era:"republic", years:"1921–2012 CE", region:"west",
    themes:["trade","science"], summary:"The 'Milkman of India' who built the Amul dairy cooperative, making India the world's largest milk producer through a revolution owned by village farmers.",
    clues:["I made India the world's largest producer of milk.","I built a cooperative called Amul from a small town in Gujarat.","They call me the Milkman of India.","My revolution was white, not green — and it was owned by village women."] },
  { id:"lakshmibai", name:"Rani Lakshmibai of Jhansi", era:"colonial", years:"1828–1858 CE", region:"north",
    themes:["women","trade"], summary:"The warrior-queen of Jhansi who fought the British in 1857 with her infant son strapped to her back, dying in battle at 29.",
    clues:["I fought the British with my baby strapped to my back.","A British general called me the most dangerous of the rebel leaders.","My kingdom's annexation under the Doctrine of Lapse sparked my revolt.","I died in battle at 29, sword in hand, defending my Jhansi."] },
  { id:"ranjit-singh", name:"Maharaja Ranjit Singh", era:"colonial", years:"1780–1839 CE", region:"north",
    themes:["trade"], summary:"The Lion of Punjab who unified the Sikh misls into a powerful, secular kingdom with a modern army, governing Hindus, Muslims, and Sikhs with equal hand.",
    clues:["I was called the Lion of Punjab.","I built a secular kingdom where Hindus, Muslims, and Sikhs served as ministers and generals.","My court housed the Koh-i-Noor diamond.","I lost an eye in childhood but became the mightiest ruler of my era."] },
  { id:"thiruvalluvar", name:"Thiruvalluvar", era:"classical", years:"~3rd century BCE", region:"south",
    themes:["language","spiritual"], summary:"Tamil poet-saint who composed the Thirukkural — 1,330 couplets on virtue, wealth, and love — considered one of the greatest works of ethics in any language.",
    clues:["My 1,330 couplets cover virtue, wealth, and love in exactly that order.","My work has been translated into over 40 languages.","A 133-foot statue of me stands at Kanyakumari, the southern tip of India.","I wrote in Tamil and my name means 'devotee of Valluvar.'"] },
  { id:"chandragupta-vikramaditya-legend", name:"Vikramaditya (legendary)", era:"classical", years:"~1st century BCE", region:"north",
    themes:["trade","language"], summary:"The legendary king of Ujjain whose name became synonymous with ideal kingship, wisdom, and justice — the Vikram Samvat calendar era begins with his reign.",
    clues:["An entire calendar era is named after me, still in use today.","I ruled from Ujjain, the city of astronomical learning.","My throne was said to be guarded by 32 speaking statues.","My name became a title claimed by every great king who followed."] }
];
