/* Bharat: 10,000 Years — Empires & Kingdoms (25+) with map region data for Empire Painter */
window.BHARAT_EMPIRES = [
  { id:"sindhu-saraswati-civ", name:"Sindhu–Saraswati Civilization", era:"sindhu-saraswati",
    start:-3300, end:-1900, capital:"Mohenjo-daro / Rakhigarhi",
    regions:["punjab","sindh","rajasthan","gujarat","haryana"],
    color:"#7fa39a", peakRuler:"(collective urban culture — no identified rulers)",
    summary:"The world's largest Bronze Age civilization, spanning the Sindhu and Saraswati basins with over 1,500 known sites — cities of extraordinary planning, shared weights, and an undeciphered script." },
  { id:"maurya", name:"Maurya Empire", era:"maurya",
    start:-321, end:-185, capital:"Pataliputra",
    regions:["punjab","haryana","rajasthan","up","bihar","bengal","odisha","mp","maharashtra","gujarat","karnataka","ap","gandhara","kashmir"],
    color:"#c9a13b", peakRuler:"Ashoka (r. 268–232 BCE)",
    summary:"India's first pan-subcontinental empire, stretching from Afghanistan to Bengal. Under Ashoka, it became history's first empire governed by principles of non-violence and welfare." },
  { id:"shunga", name:"Shunga Dynasty", era:"classical",
    start:-185, end:-73, capital:"Pataliputra / Vidisha",
    regions:["up","mp","bihar"],
    color:"#8a6e4a", peakRuler:"Pushyamitra Shunga",
    summary:"Brahmanical revivalists who patronized the expansion of Buddhist monuments at Sanchi and Bharhut while re-establishing Vedic ritual at court." },
  { id:"satavahana", name:"Satavahana Dynasty", era:"classical",
    start:-150, end:220, capital:"Pratishthana (Paithan)",
    regions:["maharashtra","ap","telangana","karnataka","mp"],
    color:"#9d6b8a", peakRuler:"Gautamiputra Satakarni",
    summary:"Lords of the Deccan for nearly four centuries, bridging north and south, patronizing Buddhist caves at Ajanta, and trading with Rome." },
  { id:"kushana", name:"Kushana Empire", era:"classical",
    start:30, end:375, capital:"Purushapura (Peshawar) / Mathura",
    regions:["gandhara","kashmir","punjab","haryana","up"],
    color:"#6b8a9d", peakRuler:"Kanishka I",
    summary:"Central Asian dynasty that became great patrons of Buddhism, Gandhara art, and Silk Road trade under Emperor Kanishka." },
  { id:"gupta", name:"Gupta Empire", era:"gupta",
    start:320, end:550, capital:"Pataliputra",
    regions:["bihar","up","mp","rajasthan","haryana","punjab","bengal","odisha","gujarat"],
    color:"#8a7fd6", peakRuler:"Chandragupta II Vikramaditya",
    summary:"India's classical golden age — the era of Aryabhata, Kalidasa, Nalanda, the Iron Pillar, and the invention of zero." },
  { id:"vakataka", name:"Vakataka Dynasty", era:"gupta",
    start:250, end:500, capital:"Nandivardhana",
    regions:["maharashtra","mp"],
    color:"#7a6a5a", peakRuler:"Harishena",
    summary:"Deccan contemporaries and marriage-allies of the Guptas, under whose patronage the later phase of Ajanta's cave murals was painted." },
  { id:"pallava", name:"Pallava Dynasty", era:"regional-empires",
    start:275, end:897, capital:"Kanchipuram",
    regions:["tn","ap"],
    color:"#c2855a", peakRuler:"Narasimhavarman I (Mamalla)",
    summary:"Architects of Mahabalipuram's shore temples and pioneers of Dravidian temple style, whose cultural influence extended across Southeast Asia." },
  { id:"chalukya-badami", name:"Chalukya (Badami)", era:"regional-empires",
    start:543, end:757, capital:"Badami (Vatapi)",
    regions:["karnataka","maharashtra","ap"],
    color:"#a8784a", peakRuler:"Pulakeshin II",
    summary:"Deccan dynasty that repelled Harsha at the Narmada and built the magnificent cave temples of Badami." },
  { id:"rashtrakuta", name:"Rashtrakuta Dynasty", era:"regional-empires",
    start:753, end:982, capital:"Manyakheta",
    regions:["karnataka","maharashtra","mp","ap","gujarat"],
    color:"#c26b4a", peakRuler:"Amoghavarsha I / Krishna I",
    summary:"The dynasty that carved the Kailasa Temple at Ellora from a single rock — the most ambitious sculptural project in human history." },
  { id:"pala", name:"Pala Dynasty", era:"regional-empires",
    start:750, end:1162, capital:"Pataliputra / Vikramapura",
    regions:["bihar","bengal"],
    color:"#5a8a6b", peakRuler:"Dharmapala",
    summary:"Buddhist kings of Bengal and Bihar who brought Nalanda and Vikramashila to their intellectual peak and exported Buddhist art across the Himalayan world." },
  { id:"pratihara", name:"Gurjara-Pratihara Dynasty", era:"regional-empires",
    start:730, end:1036, capital:"Kannauj",
    regions:["rajasthan","up","mp","haryana","gujarat"],
    color:"#8a8a5a", peakRuler:"Mihira Bhoja I",
    summary:"Guardians of India's western frontier for three centuries, repelling Arab incursions and presiding over a prosperous Gangetic heartland." },
  { id:"chola", name:"Chola Empire", era:"regional-empires",
    start:848, end:1279, capital:"Thanjavur / Gangaikonda Cholapuram",
    regions:["tn","karnataka","ap","kerala","odisha","bengal","srilanka","southeast-asia"],
    color:"#d4875a", peakRuler:"Rajaraja I / Rajendra I",
    summary:"India's greatest maritime empire — the Cholas built the Brihadeeswara Temple, conquered Sri Lanka, and sent naval expeditions to Southeast Asia." },
  { id:"pandya", name:"Pandya Dynasty", era:"classical",
    start:-600, end:1345, capital:"Madurai",
    regions:["tn","kerala"],
    color:"#9d5a6b", peakRuler:"Jatavarman Sundara Pandyan",
    summary:"One of the oldest Tamil dynasties, patrons of Sangam literature and builders of the great Meenakshi temple at Madurai." },
  { id:"chera", name:"Chera Dynasty", era:"classical",
    start:-300, end:1102, capital:"Vanchi / Mahodayapuram",
    regions:["kerala","tn"],
    color:"#5a9d7a", peakRuler:"Senguttuvan",
    summary:"Kerala's ancient ruling dynasty, celebrated in Sangam poetry and central to the Indo-Roman spice trade through the port of Muziris." },
  { id:"kakatiya", name:"Kakatiya Dynasty", era:"regional-empires",
    start:1083, end:1323, capital:"Warangal",
    regions:["telangana","ap"],
    color:"#8a5a9d", peakRuler:"Rudrama Devi",
    summary:"Telugu dynasty famous for Warangal's thousand-pillared temples, floating-brick technology, and India's most celebrated medieval queen, Rudrama Devi." },
  { id:"ahom", name:"Ahom Dynasty", era:"mughal",
    start:1228, end:1826, capital:"Charaideo / Garhgaon",
    regions:["assam"],
    color:"#6b9d5a", peakRuler:"Lachit Borphukan (general)",
    summary:"Six hundred years of unbroken sovereignty in the northeast — the Ahoms repelled every Mughal invasion, decisively at the Battle of Saraighat in 1671." },
  { id:"vijayanagara", name:"Vijayanagara Empire", era:"sultanate",
    start:1336, end:1646, capital:"Hampi (Vijayanagara)",
    regions:["karnataka","ap","tn","telangana","kerala","goa"],
    color:"#d4af5a", peakRuler:"Krishnadevaraya",
    summary:"Southern India's mightiest empire — Hampi was the world's second-largest city, a cosmopolitan capital of temples, bazaars, and multilingual courts." },
  { id:"delhi-sultanate", name:"Delhi Sultanate", era:"sultanate",
    start:1206, end:1526, capital:"Delhi",
    regions:["punjab","haryana","up","mp","rajasthan","bihar","bengal","gujarat"],
    color:"#7a8a6b", peakRuler:"Alauddin Khalji / Muhammad bin Tughlaq",
    summary:"Five successive dynasties of Turkic and Afghan origin ruled from Delhi, introducing new architectural styles while meeting sustained resistance from Rajput, Kakatiya, and other Indian powers." },
  { id:"mughal", name:"Mughal Empire", era:"mughal",
    start:1526, end:1857, capital:"Agra / Delhi",
    regions:["punjab","haryana","up","mp","rajasthan","bihar","bengal","gujarat","maharashtra","ap","karnataka","kashmir","sindh","odisha"],
    color:"#c9a05a", peakRuler:"Akbar / Shah Jahan / Aurangzeb",
    summary:"The Mughal dynasty built the Taj Mahal, administered one of the world's richest economies, and presided over a brilliant synthesis of Persian, Central Asian, and Indian culture." },
  { id:"maratha", name:"Maratha Confederacy", era:"mughal",
    start:1674, end:1818, capital:"Raigad / Pune",
    regions:["maharashtra","mp","rajasthan","gujarat","karnataka","up","punjab","odisha","bengal"],
    color:"#d47a3a", peakRuler:"Chhatrapati Shivaji Maharaj / Bajirao I",
    summary:"Founded by Shivaji as swarajya, the Maratha Confederacy grew under the Peshwas into the subcontinent's dominant power — the last great Indian empire before the colonial era." },
  { id:"sikh-empire", name:"Sikh Empire", era:"colonial",
    start:1799, end:1849, capital:"Lahore",
    regions:["punjab","kashmir","haryana"],
    color:"#5a6b9d", peakRuler:"Maharaja Ranjit Singh",
    summary:"Maharaja Ranjit Singh united the Punjab's Sikh misls into a modern, secular kingdom with a powerful Westernized army, governing Hindus, Muslims, and Sikhs with equal hand." },
  { id:"karkota-kashmir", name:"Karkota Dynasty (Kashmir)", era:"regional-empires",
    start:625, end:855, capital:"Parihaspura / Srinagara",
    regions:["kashmir"],
    color:"#5a8aaa", peakRuler:"Lalitaditya Muktapida",
    summary:"The Karkota dynasty's Lalitaditya built one of India's most expansive but least-remembered empires, reaching from Central Asia to Bengal." },
  { id:"travancore", name:"Travancore Kingdom", era:"mughal",
    start:1729, end:1949, capital:"Thiruvananthapuram",
    regions:["kerala"],
    color:"#4a8a6b", peakRuler:"Marthanda Varma",
    summary:"The kingdom that defeated the Dutch East India Company at the Battle of Colachel (1741), one of the first Asian victories over a European colonial power." },
  { id:"harsha-empire", name:"Harsha's Empire", era:"regional-empires",
    start:606, end:647, capital:"Kannauj",
    regions:["up","bihar","punjab","haryana","mp","bengal","odisha","rajasthan"],
    color:"#6b6b9d", peakRuler:"Harsha Vardhana",
    summary:"The last great north-Indian empire before the medieval fragmentation, ruled by a philosopher-king who composed plays and hosted grand Buddhist assemblies." },
  { id:"chalukya-kalyani", name:"Chalukya (Kalyani / Western)", era:"regional-empires",
    start:973, end:1189, capital:"Kalyani",
    regions:["karnataka","maharashtra","ap"],
    color:"#9d8a5a", peakRuler:"Vikramaditya VI",
    summary:"The later Chalukyas of Kalyani revived Chalukyan power in the Deccan, patronizing temple architecture and the Kannada literary tradition." }
];
